buildrunner: 
  script: mvn clean package -DskipTests
releaserunner: 
  script: mvn clean package -DskipTests
environment_image: sjc-docker-registry.ustream-adm.in/build-tools/ci-base-images/jvm-trusty:latest
extensions:
  archiva_uploader:
    paths:
    - curator-recipes/target/curator-recipes-*.jar